### ISSUE TITLE
Crashing into yourself in a straightline

### ISSUE THREAD

**Issue by theosanderson** [sungyeonkwon/multitask-snake#2]
Dear developer,

What a great game. I found the multi-tasking element very interesting. However I have identified an important issue which I think is worthy of your consideration.

Suppose your snake is going right, and you wish to go down and left. You press down, and then press left. But your snake has not had time to move down before it goes left. Your snake ends up hitting its own neck, and dying. But the snake is still in a horizontal line so this does not make sense:
![image](https://user-images.githubusercontent.com/19732295/121755777-f167ed00-cb0f-11eb-989b-425351216552.png)

Suggestions: either the left move should be cancelled, or it should be queued for after the down move has taken place.

Thank you for considering this important issue.

Kind regards

**Comment by sungyeonkwon** [comment]
Hi Theo, 

Thank you very much for raising this very important issue.
2128ce8d0b833f7f683af65e31231c07d51f768a should solve this issue.

In fact, throttling needs to be implemented throughout the app, I'll add them along once I get the promised ice cream from you. Thanks for the flag and the future ice cream.

![giphy-downsized](https://user-images.githubusercontent.com/25865179/121776651-fe272800-cb85-11eb-916b-e28787ada4d6.gif)
