### ISSUE TITLE
It is possible to eat food without entering food square

### ISSUE THREAD

**Issue by theosanderson** [sungyeonkwon/multitask-snake#3]
Reproduction:
Head towards food. As you are about to enter food square, food disappears. Then turn and you never enter food square.

Expected result:
Food disappears as you enter the food square

**Comment by sungyeonkwon** [comment]
Very good spotting, the snake was eating food with its future head! Fixed on 433500a70515aeae02b457e5ff86aaa4fb7c3e73

**Comment by theosanderson** [comment]
OK Sung. Thank you for addressing this issue. I will close this now. Best regards.
